## Run on container environment
sudo: false

language: php

services:
  - mongodb

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    
## Cache composer bits
cache:
  directories:
    - $HOME/.composer/cache
    
before_script:
  # Set up Composer
  - composer self-update || true
  - composer install

script:
  - php ./vendor/bin/phpunit

after_script:
  - php ./vendor/bin/codacycoverage phpunit ../web/php-bash-writer/coverage
